type: object
requires: ["gitter_api_key", "matrix_homeserver", "matrix_user_domain", "username_template"]
properties:
  gitter_api_key:
    type: string
  matrix_homeserver:
    type: string
  matrix_user_domain:
    type: string
  username_template:
    type: string
  matrix_admin_room:
    type: string
  name_mangling:
    type: array
    items:
      type: object
      properties:
        pattern:
          type: string
        template:
          type: string
  enable_metrics:
    type: boolean
