type: object
requires: ["gitter_api_key", "matrix_homeserver", "matrix_user_domain"]
properties:
  gitter_api_key:
    type: string
  matrix_homeserver:
    type: string
  matrix_user_domain:
    type: string
  matrix_admin_room:
    type: string
