# Obtain this key from
#   https://developer.gitter.im/apps
gitter_api_key: "0123456789ABCDEF"

# The location of the homeserver this AS is configured for
matrix_homeserver: "http://example.com:8008"
# External url for media 
matrix_external_url: "https://matrix.org"

# The domain for locally-created users
matrix_user_domain: "example.com"

# The storage location for data files. This should be something like /data for docker.
# data_dir: "."

# A template to use to generate locally-created usernames. This string must
#   contain ${USER} somewhere inside it.
username_template: "_gitter_${USER}"

# A list of rules to define how to generate `usernames` on the gitter side
# of the relaybot for various patterns of matrix user ID
name_mangling:
  - pattern: "@irc_(.*):example.com"
    template: "$1 (IRC)"

logging:
    console: "debug"
    files:
        -   "debug.log": "debug"
    maxFiles: 1

enable_portals: false
alias_template: "gitter_${ROOM}"
